# Generated by Django 2.2.2 on 2019-07-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosco_app', '0003_auto_20190728_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egreso',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_producto',
            field=models.CharField(max_length=100, unique=True, verbose_name='Codigo de Producto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cuit',
            field=models.BigIntegerField(unique=True),
        ),
    ]
